[package]
name = "milli_py"
version = "1.1.1"
edition = "2021"
authors = ["Alexandro Sanchez Bach <alexandro@phi.nz>"]

[lib]
name = "milli"

# Needed to produce a shared library for Python.
crate-type = ["cdylib"]

[dependencies]
milli = { path = "meilisearch/milli" }
pyo3 = { version = "0.18.1", features = ["extension-module"] }
serde_json = { version = "1.0.93" }
serde = { version = "1.0.152" }
