name: ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
        with: 
          submodules: true

      # Select Rust toolchain
      - name: Select Rust toolchain
        run: |
          rustup set auto-self-update disable
          rustup toolchain install stable --profile minimal

      # Install and cache Cargo dependencies
      - uses: Swatinem/rust-cache@v2
      - name: Check package
        run: |
          cargo check

      # Install and cache Python dependencies
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      # Build and test package
      - name: Build package
        run: |
          pip3 install maturin
          python3 -m maturin build -i ${{ matrix.python-version }}
